version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "8080:8080"  # Flower server port
    command: python src/server/server.py
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  client1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
      - ../data/client1:/app/data
    depends_on:
      - server
    command: python src/train.py --client_id=1
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  client2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
      - ../data/client2:/app/data
    depends_on:
      - server
    command: python src/train.py --client_id=2
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  fl_network:
    driver: bridge